/* Generated by re/tools/genpal.py from the palettes at DS:5f15 in
 * SPFIX62.EXE.  Channels are 4-bit, as in PALETTES.DAT. */
#ifndef TITLEPAL_H
#define TITLEPAL_H
#include <stdint.h>

enum { TP_TITLE, TP_CREDITS, TP_CREDITS_BLANK, TP_COUNT };

static const uint8_t title_pal[TP_COUNT][16][3] = {
    { /* TITLE */
        {  2,  3,  5 },
        { 13, 10,  4 },
        {  2,  6,  6 },
        {  3,  9,  9 },
        { 11,  8,  3 },
        {  2,  7,  7 },
        {  8,  6, 13 },
        {  6,  4, 11 },
        {  9,  1,  0 },
        { 11,  1,  0 },
        { 13,  1,  0 },
        { 15,  1,  0 },
        { 15,  6,  4 },
        {  2,  5,  6 },
        { 15, 12,  6 },
        { 12, 12, 13 },
    },
    { /* CREDITS */
        {  0,  0,  0 },
        { 15, 15, 15 },
        {  6,  6,  6 },
        { 10, 10, 10 },
        { 10, 10, 10 },
        { 11, 11, 11 },
        { 14,  1,  1 },
        {  9,  9,  9 },
        {  1,  3,  7 },
        {  8,  8,  8 },
        {  9,  0,  0 },
        { 11,  0,  0 },
        {  0,  2, 10 },
        {  5,  5,  5 },
        {  6,  6,  6 },
        {  8,  8,  8 },
    },
    { /* CREDITS_BLANK */
        {  0,  0,  0 },
        { 15, 15, 15 },
        {  8,  8,  8 },
        { 10, 10, 10 },
        { 10, 10, 10 },
        { 11, 11, 11 },
        { 14,  1,  1 },
        {  9,  9,  9 },
        {  8,  8,  8 },
        {  8,  8,  8 },
        {  9,  0,  0 },
        { 11,  0,  0 },
        {  8,  8,  8 },
        {  5,  5,  5 },
        {  6,  6,  6 },
        {  8,  8,  8 },
    },
};

#endif
